/**
 * Two questions about the business behind the website, both of which have to
 * be answered before anybody is written to.
 *
 *   Is it still trading?   Emailing a business that closed in 2019 about
 *                          rebuilding its website is worse than useless. A
 *                          neglected site and an abandoned one look almost
 *                          identical to a checker that only reads markup, and
 *                          the difference is the whole email.
 *
 *   Can it afford this?    A rebuild is nine hundred dollars. Sending that
 *                          proposal to a one-man shop that is barely covering
 *                          rent is not a sale, it is an insult with a price on
 *                          it. Some of those businesses need the work most, so
 *                          the answer is not to drop them - it is to offer it
 *                          free and mean it.
 *
 * Pure functions over text that was already fetched. No network, no browser,
 * so every rule here can be tested against a string.
 */

/** Said outright. Nothing else in here is as reliable as a business saying so. */
const CLOSED_OUTRIGHT = /\b(permanently closed|we (?:have )?closed (?:our|for good|permanently)|no longer in business|out of business|ceased trading|has closed its doors|going out of business sale|closing down sale|business is closed)\b/i;

/** A site that never launched is not a rebuild, it is a different job. */
const NOT_LAUNCHED = /\b(coming soon|under construction|site (?:is )?(?:currently )?being (?:re)?built|check back soon|launching soon|page is under development)\b/i;

/** Signs somebody is still turning up: things only a trading business writes. */
const STILL_TRADING = /\b(open (?:today|now|daily|mon|tue|wed|thu|fri|sat|sun)|book (?:online|now|an appointment)|request (?:a )?quote|order online|schedule (?:service|an appointment)|call (?:us )?today|now hiring|we are hiring|accepting new (?:patients|clients|customers))\b/i;

/**
 * Is anybody still running this business?
 *
 * The copyright year on its own is not evidence. Plenty of busy shops have a
 * footer that has said 2017 for years, and a dead site can have a copyright
 * line generated by script that says this year forever. What settles it is
 * the combination: nothing dated recently anywhere on the page, a stale
 * footer, and no wording that a trading business would bother to write.
 */
export function vitality({ text = "", copyrightYear = null, latestYearOnPage = null, thisYear = new Date().getFullYear() } = {}) {
  const reasons = [];

  if (CLOSED_OUTRIGHT.test(text)) {
    return { state: "closed", reasons: ["the site says the business has closed"], contactable: false };
  }
  if (NOT_LAUNCHED.test(text)) {
    return { state: "unbuilt", reasons: ["the site is a coming-soon or under-construction page"], contactable: false };
  }

  const trading = STILL_TRADING.test(text);
  const copyrightAge = copyrightYear == null ? null : thisYear - copyrightYear;
  const contentAge = latestYearOnPage == null ? null : thisYear - latestYearOnPage;

  if (trading) reasons.push("the page asks visitors to call, book or order");
  if (contentAge !== null && contentAge <= 1) reasons.push(`something on the page is dated ${latestYearOnPage}`);
  if (copyrightAge !== null && copyrightAge <= 1) reasons.push("the footer is current");

  /*
    "Quiet" rather than "closed", deliberately. Nothing here proves a business
    has stopped; it only says there is no sign of life on the homepage, which
    is a reason to look before writing, not a reason to write it off. The one
    thing treated as proof is the business saying so itself, above.
  */
  const noSignOfLife = !trading
    && (copyrightAge === null || copyrightAge >= 3)
    && (contentAge === null || contentAge >= 3);

  if (noSignOfLife) {
    const why = [];
    if (copyrightAge !== null) why.push(`the footer still says ${copyrightYear}`);
    if (contentAge !== null) why.push(`nothing on the page is dated later than ${latestYearOnPage}`);
    why.push("and nothing invites a visitor to get in touch");
    return { state: "quiet", reasons: why, contactable: true };
  }

  return { state: "active", reasons: reasons.length ? reasons : ["no sign of trouble"], contactable: true };
}

/** Things only a business with staff and money to spend puts on a homepage. */
const SCALE_MARKERS = [
  [/\b(careers?|now hiring|we are hiring|join our team|apply now|open positions)\b/i, "advertising jobs"],
  [/\b(our team|meet the team|our staff|technicians|our crew|employees)\b/i, "a team page"],
  [/\b(locations?|branches|offices in|serving (?:the )?(?:greater )?[A-Z][a-z]+ (?:metro|area|county))\b/, "more than one location or a service area"],
  [/\b(commercial|industrial|contract|wholesale|enterprise|municipal)\b/i, "commercial or industrial customers"],
  [/\b(licensed(?:,| and)? (?:bonded(?:,| and)? )?(?:and )?insured|fully insured|bonded)\b/i, "licensing and insurance"],
  [/\b(fleet|trucks|vans|service vehicles)\b/i, "vehicles"],
  [/\b(since (?:18|19|20)\d\d|established (?:18|19|20)\d\d|over \d{2}\+? years|\d{2}\+ years (?:of )?(?:experience|in business))\b/i, "years in business"],
  [/\b(financing available|payment plans|net 30|purchase orders?|accounts?)\b/i, "trade terms"],
];

/** Things that say the whole business is one or two people. */
const SMALL_MARKERS = [
  [/\b(family(?:[ -])owned|family run|mom and pop|husband and wife|owner[ -]operated|small family)\b/i, "family run"],
  [/\b(just me|one[ -]man|sole proprietor|solo)\b/i, "a one-person business"],
];

/**
 * Roughly how big the business is, from what its own homepage says.
 *
 * This is a judgement about who to send which email to, not a credit check,
 * and it is deliberately cautious in one direction: being wrong about a big
 * company costs a slightly odd email, being wrong about a struggling one
 * costs a nine-hundred-dollar proposal landing on somebody who cannot pay it.
 * So it takes real evidence to call a business established, and very little
 * to call it micro.
 */
export function sizeOf({ text = "", ownPageCount = null, freeTier = false, reviewCount = null } = {}) {
  const found = [];
  for (const [re, why] of SCALE_MARKERS) if (re.test(text)) found.push(why);
  const small = [];
  for (const [re, why] of SMALL_MARKERS) if (re.test(text)) small.push(why);

  // A site of one page is somebody who has not invested in a site, which
  // usually means they have not got it to invest.
  const onePager = ownPageCount !== null && ownPageCount <= 1;
  if (onePager) small.push("a single-page site");
  if (freeTier) small.push("a free website-builder plan");

  let size, why;
  if (found.length >= 3 && !freeTier) {
    size = "established";
    why = found.slice(0, 3);
  } else if (found.length >= 1 && !onePager && !freeTier) {
    size = "small";
    why = found.slice(0, 3);
  } else {
    size = "micro";
    why = small.length ? small.slice(0, 3) : ["nothing on the page suggests staff, locations or trade customers"];
  }

  /*
    Reviews only ever move this upward. Plenty of busy little shops have no
    reviews at all on the source this runs against, so a low count proves
    nothing - but a hundred and eighty of them proves somebody is busy.
  */
  if (reviewCount != null && reviewCount >= 120 && size === "micro") {
    size = "small";
    why = [`${reviewCount} reviews, so people are finding them`];
  }

  return {
    size,
    reasons: why,
    /*
      Who gets the free offer. It has to be both halves: a tiny business with
      a perfectly good website does not need one, and a big company with an
      awful website can pay. The score half is applied by the caller, which is
      where the score lives.
    */
    offerFree: size === "micro",
  };
}

/** The newest year written anywhere a visitor can see, ignoring the future. */
export function latestYearIn(text = "", thisYear = new Date().getFullYear()) {
  let newest = null;
  for (const m of text.matchAll(/\b(19[89]\d|20[0-4]\d)\b/g)) {
    const year = Number(m[1]);
    if (year > thisYear + 1) continue;
    if (newest === null || year > newest) newest = year;
  }
  return newest;
}
